### PR TITLE
Added the ability to pass in a on_refresh callback function

### PR DESCRIPTION
**Pull request by Threetwosevensixseven**
Added the ability to pass in a callback function into settings.on_refresh. This can be used to do post-refresh processing, e.g. container resizing.
Added an example to index.html.
Added a purple info class to the stylesheet.

### CODE REVIEW

**Comment by denhartog** [comment]
Thanks for the contribution! I'll take a look at your code this coming week. I think a callback on refresh will be a great addition!

**Comment by Threetwosevensixseven** [comment]
Just a small enhancement! I have almost added a second on_render_content callback too, so hold fire on reviewing the code until later on today please :)

**Comment by Threetwosevensixseven** [comment]
Ok, I'm finished! :)

**Comment by Threetwosevensixseven** [comment]
It's set up so it all works as standard unless you opt in to the callbacks. Hopefully the examples are self-explanatory

**Comment by denhartog** [comment]
I had a chance to pull your request and explore the modifications made and see the value in having a callback option which fires after each complete refresh. Simple enough.

`on_refresh_content` seems overly complex and requires Users to know the internal variable names of simple-pagination, which is unacceptable. Further, the content of the navigation buttons is already fully customizable, which leaves us with the fact that only the start `page_x_of_x_content` and `showing_x_of_x_content` is customizable, not the separator(s) or ending:

PROPOSAL:
POSSIBILITIES for `page_x_of_x_content` and `showing_x_of_x_content`:
1. each stays a string with required '{vars}' which gets formatted using regex;
2. each becomes an array of strings: ['start ', ' separator ', ' end'];
3. each becomes three/four different variables.

1 is out of the question because like your current `on_refresh_content` is requires Users to know internal variable names. So it's 2 or 3. 3 seems to be the most explicit and being primarily a Python developer I relish in explicits ;)

CURRENT INPUT:

```
$.fn.simplePagination.defaults = {
    page_x_of_x_content: 'Page',
    showing_x_of_x_content: 'Showing'
};
```

CURRENT OUTPUT:
'Page X of X'
'Showing X-X of X'

FUTURE INPUT:

```
$.fn.simplePagination.defaults = {
    //#1
    page_x_of_x_content: 'Start {page_number} separator {page_count} end',
    //#2
    page_x_of_x_content: ['start ', ' separator ', ' end'],
    //#3
    page_x_of_x_start: 'Page ',
    page_x_of_x_separator: ' of ',
    page_x_of_x_end: '',
    //
    showing_x_of_x_start: 'Showing ',
    showing_x_of_x_range_separator: '-',
    showing_x_of_x_total_separator: ' of ',
    showing_x_of_x_end: ''
};
```

FUTURE OUTPUT (given the above defaults):
`Page X of X`, which would internally be:
`page_x_of_x_start + X + page_x_of_x_separator + X + page_x_of_x_end`
AND
`Showing X-X of X`, which internally would be:
`showing_x_of_x_start + X + showing_x_of_x_range_separator + X + showing_x_of_x_total_separator + X + showing_x_of_x_end`

Adding a few new variables seems to be incredibly more simple than your proposal; what am I missing?

**Comment by Threetwosevensixseven** [comment]
Apologies Douglas. I changed employer and never followed up on this. All the best :) Robin

**Comment by denhartog** [comment]
No worries Robin. Hope you've enjoyed the employer change :)

**Pull request closed without merging**
